### ISSUE TITLE
Not fully clear how to enter tom type in field if you don't know you need brackets 

### ISSUE THREAD

**Issue by peter-zenk** [oswald2/DGPatchMaker#13]
A minor issue (?):

![Screenshot_2020-07-03_20-00-48](https://user-images.githubusercontent.com/67412544/86490544-07015e00-bd68-11ea-8ffa-0eaf6c1ab2ee.png)

In the instrument pane - when entering the type from the pop-up it is not really clear how to enter the tom type:

I tried  "Tom RackTom 1"  "RackTom 1" and anything. 
From the YT video eventually I learned it has to be "Tom (RackTom 1)" 

This is not obvious: 

Would it be a big issue to make it a drop down menu as well, like for the channel?

Thanks :-)

![Screenshot_2020-07-03_20-00-48](https://user-images.githubusercontent.com/67412544/86490544-07015e00-bd68-11ea-8ffa-0eaf6c1ab2ee.png)

**Comment by oswald2** [comment]
Ok, will do. I agree that the current solution is not very pretty.

**Comment by peter-zenk** [comment]
Thx, never mind
managed to get a kit compiled with a joint effort of DG PM and vi -> works fine in Ardour. 
Saves a lot of work
